### ISSUE TITLE
Code Unreachable

### ISSUE THREAD

**Issue by yamamushi** [chew-z/SwissEphem#3]
I think there is a typo here:

https://github.com/chew-z/GoHoroscope/blob/d89b137278df1cca934f7e2a295ff3679afdbba3/astro.go#L235

There's a trailing bracket after the comment on the line, which renders the following logic unreachable.

If you move the bracket out of the comment, you can delete the bracket on line 254:

https://github.com/chew-z/GoHoroscope/blob/d89b137278df1cca934f7e2a295ff3679afdbba3/astro.go#L254

To achieve what I believe is intended with this function.

**Comment by chew-z** [comment]
Yes, you are right... Good catch ;-) 

Otherwise we might have division by zero in 236....
